spring.application.name=demo

#DB CONFIG

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JWT SECRET

jwt.secret=Qm9uTGVhcm5Kd3RTZWNyZXRLZXlGb3JQcm9qZWN0MjAyNg==

#FRONT-END ENDPOINT

app.front_endpoint=http://localhost:5173